'use client'
import './globals.css'
import { Poppins } from 'next/font/google'
import {AppContextProvider} from '../libs/myAppContext'
const inter = Poppins({ subsets: ['latin'] , weight:['300','400'] })

export const MetaData = {
  title: 'GUPUTA | Sinhala ChatGPT Interface',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppContextProvider>
      <body className={inter.className}>{children}</body>
      </AppContextProvider>
    </html>
  )
}
